name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout the repo'
        uses: actions/checkout@v3

      - name: 'Set tag'
        run: echo "BUILD_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 'Build image '
        run: |
          docker buildx build . --tag ghcr.io/${{ github.actor }}/04-03-broken:${BUILD_TAG} --tag ghcr.io/${{ github.actor }}/04-03-broken:latest
          docker push ghcr.io/${{ github.actor }}/04-03-broken:${BUILD_TAG}
          docker push ghcr.io/${{ github.actor }}/04-03-broken:latest
